# Generated by Django 4.2.4 on 2023-09-12 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Milo', 'Milo'), ('Milk', 'Milk'), ('Strawberry', 'Strawberry'), ('Strawberry Shake', 'Strawberry Shake'), ('Avocado Juice', 'Avocado Juice'), ('Kiwi', 'Kiwi'), ('Pizza', 'Pizza'), ('Chicken Pie', 'Chicken Pie'), ('Sandwich', 'Sandwich')], max_length=100, null=True)),
                ('unityprice', models.CharField(choices=[('ML 400', 'ML 400'), ('MK 500', 'MK 500 '), ('STB 600', 'STB 600'), ('SBS 500', 'SBS 500'), ('AV 700', 'AV 700'), ('KW 300', 'KW 300'), ('PZ 900', 'PZ 900'), ('CP 450', 'CP 450'), ('SW 850', 'SW 850')], max_length=100, null=True)),
                ('quantity', models.PositiveIntegerField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Product',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unity_price', models.CharField(choices=[('Milo', '400  Milo'), ('Milk', '500  Milk'), ('Strawberry', '600  Strawberry'), ('Strawberry Shake', '500  Strawberry Shake'), ('Avocado Juice', '700  Avocado Juice'), ('Kiwi', '300  Kiwi'), ('Pizza', '900  Pizza'), ('Chicken Pie', '450  Chicken Pie'), ('Sandwich', '850  Sandwich')], max_length=100, null=True)),
                ('sellingprice', models.PositiveIntegerField(null=True)),
                ('order_quantity', models.PositiveIntegerField(null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.product')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Order',
            },
        ),
    ]
