# Generated by Django 4.2.4 on 2023-09-12 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_product_unityprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unityprice',
            field=models.CharField(choices=[('ML 400', '400 ml'), ('MK 500', '500 mk'), ('STB 600', '600 sb'), ('SBS 500', '500 ssh'), ('AV 700', '700 av'), ('KW 300', '300 kw'), ('PZ 900', '900 pz'), ('CP 450', '450 cp'), ('SW 850', '850 sw')], max_length=100, null=True),
        ),
    ]
